"""AttemptQuestion column display_order

Revision ID: 20c97fb865c2
Revises: ebf1b64afd69
Create Date: 2026-09-24 20:36:31.150423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c97fb865c2'
down_revision = 'ebf1b64afd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_questions', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
