"""add scheduled_release_at to tests

Revision ID: 2c0b04b7148b
Revises: 068373c4eb89
Create Date: 2026-09-25 06:43:56.001042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0b04b7148b'
down_revision = '068373c4eb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_release_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('scheduled_release_at')

    # ### end Alembic commands ###
