"""prepare for case-insensitive email uniqueness

Revision ID: 85f0ae7827fa
Revises: fb034805aebd
Create Date: 2026-09-27 21:38:17.626980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f0ae7827fa'
down_revision = 'fb034805aebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.execute("CREATE UNIQUE INDEX ix_users_email_lower ON users (lower(email))")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.execute('DROP INDEX ix_users_email_lower')
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    # ### end Alembic commands ###
