"""validity_hours column

Revision ID: ebf1b64afd69
Revises: e7066833f1f8
Create Date: 2026-09-22 23:52:29.716983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf1b64afd69'
down_revision = 'e7066833f1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity_hours', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('validity_hours')

    # ### end Alembic commands ###
