"""add grade_history table

Revision ID: fb034805aebd
Revises: 2c0b04b7148b
Create Date: 2026-09-25 13:07:14.590619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb034805aebd'
down_revision = '2c0b04b7148b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('previous_is_correct', sa.Boolean(), nullable=True),
    sa.Column('previous_points', sa.Integer(), nullable=True),
    sa.Column('new_is_correct', sa.Boolean(), nullable=True),
    sa.Column('new_points', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_history')
    # ### end Alembic commands ###
